blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/your-org/your-repo/discussions/new?category=q-a
    about: Ask questions and get help from the community
  - name: 💡 Feature Discussion
    url: https://github.com/your-org/your-repo/discussions/new?category=ideas
    about: Discuss and propose new ideas before creating a formal feature request
  - name: 📚 Documentation
    url: https://github.com/your-org/your-repo/wiki
    about: Browse project documentation and guides
  - name: 🔒 Security Vulnerability (Private)
    url: https://github.com/your-org/your-repo/security/advisories/new
    about: Report security vulnerabilities privately through GitHub Security Advisories
