name: UI Tests

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'ui/**'
      - '.github/workflows/ui-tests.yml'
  push:
    branches: [ main ]
    paths:
      - 'ui/**'

jobs:
  lint-and-type-check:
    name: Lint & Type Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ui/package-lock.json

    - name: Install dependencies
      working-directory: ./ui
      run: npm ci

    - name: Run ESLint
      working-directory: ./ui
      run: npm run lint

    - name: Type check
      working-directory: ./ui
      run: npx tsc --noEmit

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ui/package-lock.json

    - name: Install dependencies
      working-directory: ./ui
      run: npm ci

    - name: Build
      working-directory: ./ui
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ui-build
        path: ui/.next

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run npm audit
      working-directory: ./ui
      run: npm audit --audit-level=moderate || true

    - name: Check for outdated dependencies
      working-directory: ./ui
      run: npm outdated || true
